from enum import Enum


class AppCode(str, Enum):
    ACTION = "ACTION"
    ACTION_CHAT = "ACTION_CHAT"
    ACTION_MARKET = "ACTION_MARKET"
    ACTION_RUN = "ACTION_RUN"
    ACTION_GRAPH = "ACTION_GRAPH"
    ACTION_GRAPH_RUN = "ACTION_GRAPH_RUN"
    AGENT = "AGENT"
    API = "API"
    AUTH = "AUTH"
    DATASTORE = "DATASTORE"
    EVENT_RESULT = "EVENT_RESULT"
    SUBSCRIPTION = "SUBSCRIPTION"
    USER = "USER"
