[tool.poetry]
name = "autobots"
version = "0.1.0"
description = ""
authors = ["Anurag Jha <toanuragjha@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
fastapi = "^0.105.0"
uvicorn = "^0.25.0"
pydantic = {extras = ["dotenv", "email"], version = "^2.4.1"}
pydantic-settings = "^2.0.2"
loguru = "^0.7.2"
openai = {extras = ["datalib"], version = "^1.6.0"}
pytest-asyncio = "^0.23.2"
selenium = "^4.16.0"
stability-sdk = "^0.8.3"
aiohttp = "^3.8.6"
pytest-xdist = "^3.3.1"
duckduckgo-search = "^4.1.0"
pinecone-client = {extras = ["grpc"], version = "^V3.0.0rc2"}
boto3 = "^1.34.5"
boto3-stubs = {extras = ["essential"], version = "^1.34.5"}
tiktoken = "^0.5.1"
pillow = "^10.0.0"
ddtrace = "^2.0.2"
sqlalchemy = "^2.0.21"
psycopg2 = "^2.9.9"
supabase = "^2.0.3"
python-jose = "^3.3.0"
python-multipart = "^0.0.6"
redis = "^5.0.1"
pymongo = "^4.4.1"
aiodns = "^3.1.0"
jinja2 = "^3.1.2"
networkx = "^3.1"
unstructured-client = "^0.15.0"
webdriver-manager = "^4.0.1"
pytest-timeout = "^2.2.0"
psutil = "^5.9.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
