[tool.poetry]
name = "autobots"
version = "0.1.0"
description = ""
authors = ["Anurag Jha <toanuragjha@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
fastapi = "0.109.0"
uvicorn = "0.27.0"
pydantic = {extras = ["dotenv", "email"], version = "2.6.0"}
pydantic-settings = "^2.0.2"
loguru = "^0.7.2"
openai = {extras = ["datalib"], version = "1.10.0"}
pytest-asyncio = "0.23.4"
selenium = "4.17.2"
#stability-sdk = "^0.8.3"
aiohttp = "3.9.3"
pytest-xdist = "^3.3.1"
duckduckgo-search = "4.4"
pinecone-client = {extras = ["grpc"], version = "3.0.2"}
boto3 = "1.34.33"
boto3-stubs = {extras = ["essential"], version = "1.34.33"}
tiktoken = "^0.5.1"
pillow = "^10.0.0"
ddtrace = "2.5.2"
sqlalchemy = "^2.0.21"
psycopg2 = "^2.9.9"
supabase = "^2.0.3"
python-jose = "^3.3.0"
python-multipart = "^0.0.6"
redis = "^5.0.1"
pymongo = "^4.4.1"
aiodns = "^3.1.0"
jinja2 = "^3.1.2"
networkx = "^3.1"
unstructured-client = "0.16.0"
webdriver-manager = "^4.0.1"
pytest-timeout = "^2.2.0"
psutil = "^5.9.7"
retry = "^0.9.2"
replicate = "^0.23.1"
pg8000 = "^1.30.4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.2.1"
pre-commit = "^3.6.1"

[tool.ruff]
fix = true
line-length = 88  # defaults to 88
ignore = ["E501"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
