[tool.poetry]
name = "autobots"
version = "0.1.0"
description = ""
authors = ["Anurag Jha <toanuragjha@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.98.0"
uvicorn = "^0.22.0"
pydantic = {extras = ["dotenv", "email"], version = "^1.10.9"}
loguru = "^0.7.0"
openai = {extras = ["datalib"], version = "^0.27.8"}
pytest-asyncio = "^0.21.0"
selenium = "^4.10.0"
stability-sdk = "^0.8.2"
aiohttp = "^3.8.4"
pytest-xdist = "^3.3.1"
duckduckgo-search = "^3.8.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
