name: Build

on:
  workflow_dispatch:
  workflow_call:

env:
  IMAGE_TAG: ${{ github.ref_name }}
  # Datadog Environment
  DD_ENV: ${{ github.ref_name }}
  # Datadog Version
  DD_VERSION: ${{ github.ref_name }}-${{ github.run_number }}
  # DO CI
  DO_CI: ${{ github.ref == 'refs/heads/main' && true || false }}
  # DO CD
  DO_CD: ${{ github.ref == 'refs/heads/main' && true || false }}

jobs:

  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Build Docker image
        run: docker build -t registry.gitlab.com/meetkiwi/autobots:${IMAGE_TAG} --build-arg DD_ENV=${DD_ENV} --build-arg DD_VERSION=${DD_VERSION} .

      - name: Push Docker image to GitLab Container Registry
        run: |
          docker push registry.gitlab.com/meetkiwi/autobots:${IMAGE_TAG}
