name: Build Docker Image

on:
  push:
    branches:
      - main
    tags:
      - v**
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare for Tests
        run: |
          pip3 install poetry
          poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

      - name: Run Tests
#        working-directory: ./app
        run: |
          python -m pytest -s
        env:
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STABILITY_HOST: ${{ secrets.STABILITY_HOST }}
          STABILITY_KEY: ${{ secrets.STABILITY_KEY }}

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Build Docker image
        run: docker build -t registry.gitlab.com/meetkiwi/autobots:${IMAGE_TAG} .
#        working-directory: ./app

      - name: Push Docker image to GitLab Container Registry
        run: |
          docker push registry.gitlab.com/meetkiwi/autobots:${IMAGE_TAG}
