name: CICD

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.ref_name }}
  # Datadog Environment
  DD_ENV: ${{ github.ref_name }}
  # Datadog Version
  DD_VERSION: ${{ github.ref_name }}-${{ github.run_number }}
  # DO CI
  DO_CI: ${{ github.ref == 'refs/heads/main' && true || false }}
  # DO CD
  DO_CD: ${{ github.ref == 'refs/heads/main' && true || false }}

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tests
        uses: ./.github/actions/tests.yaml

#  build:
#    needs: [tests]
#    if: ${{ github.ref == 'refs/heads/main' }}
#    uses: ./.github/actions/build.yaml
#
#  deploy:
#    needs: [build]
#    if: ${{ github.ref == 'refs/heads/main' }}
#    uses: ./.github/actions/deployment-dev.yaml