name: Continuous Tests

on:
  workflow_dispatch:
  workflow_call:

env:
  IMAGE_TAG: ${{ github.ref_name }}

jobs:

  tests:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare for Tests
        run: |
          pip3 install poetry
          poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

      - name: Run Tests
#        working-directory: ./tests
        run: |
          python -m pytest -vv -n 5 --timeout=300
        env:
          ENV: ${{ secrets.ENV }}
          COOKIE_DOMAIN: ${{ secrets.COOKIE_DOMAIN }}
          ALLOW_ORIGINS: ${{ secrets.ALLOW_ORIGINS }}
          SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}
          SQLALCHEMY_DATABASE_SCHEMA: ${{ secrets.SQLALCHEMY_DATABASE_SCHEMA }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          MONGO_CONN: ${{ secrets.MONGO_CONN }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STABILITY_HOST: ${{ secrets.STABILITY_HOST }}
          STABILITY_KEY: ${{ secrets.STABILITY_KEY }}
          STABLE_DIFFUSION_API_KEY: ${{ secrets.STABLE_DIFFUSION_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_S3_BUCKET_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}
          AWS_S3_PUBLIC_BUCKET_NAME: ${{ secrets.AWS_S3_PUBLIC_BUCKET_NAME }}
          AWS_S3_PUBLIC_BUCKET_IMAGE_FOLDER: ${{ secrets.AWS_S3_PUBLIC_BUCKET_IMAGE_FOLDER }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          UNSTRUCTURED_API_KEY: ${{ secrets.UNSTRUCTURED_API_KEY }}
          REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}
          DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          USEAPI_NET_TOKEN: ${{ secrets.USEAPI_NET_TOKEN }}
          USEAPI_NET_END_POINT_URL: ${{ secrets.USEAPI_NET_END_POINT_URL }}
          CLAID_API_KEY: ${{ secrets.CLAID_API_KEY }}
          CLAID_SIDE_S3_BUCKET: ${{ secrets.CLAID_SIDE_S3_BUCKET }}
          CLAID_PATH_PREFIX: ${{ secrets.CLAID_PATH_PREFIX }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          OPUS_API_KEY: ${{ secrets.OPUS_API_KEY }}


