name: Continuous Tests

on:
  push:
    branches:
      - '*'
      - '!main'
    tags:
      - '!v**'
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.ref_name }}

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare for Tests
        run: |
          pip3 install poetry
          poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

      - name: Run Tests
#        working-directory: ./app
        run: |
          python -m pytest -vv -n 5
        env:
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STABILITY_HOST: ${{ secrets.STABILITY_HOST }}
          STABILITY_KEY: ${{ secrets.STABILITY_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
